site_name: osquery
theme: readthedocs

docs_dir: docs/wiki
site_dir: build/wiki
pages:
- ['index.md', 'Introduction', 'Welcome to osquery']

- ['introduction/overview.md', 'Introduction', 'Features Overview']
- ['introduction/using-osqueryi.md', 'Introduction', 'osqueryi (shell)']
- ['introduction/using-osqueryd.md', 'Introduction', 'osqueryd (daemon)']

- ['installation/install-osx.md', 'Installation', 'Install on OS X']
- ['installation/install-linux.md', 'Installation', 'Install on Linux']
- ['installation/cli-flags.md', 'Installation', 'Command Line Flags']
- ['installation/custom-packages.md', 'Installation', 'Optional: Custom Packages']

- ['deployment/configuration.md', 'Deployment', 'Configuration']
- ['deployment/logging.md', 'Deployment', 'Logging']
- ['deployment/log-aggregation.md', 'Deployment', 'Aggregating Logs']
- ['deployment/performance-safety.md', 'Deployment', 'Performance Safety']
- ['deployment/anomaly-detection.md', 'Deployment', 'Anomaly Detection']
- ['deployment/extensions.md', 'Deployment', 'Extensions']
- ['deployment/file-integrity-monitoring.md', 'Deployment', 'File Integrity Monitoring']
- ['deployment/yara.md', 'Deployment', 'YARA Scanning']
- ['deployment/remote.md', 'Deployment', 'Remote settings']

- ['development/building.md', 'Development', 'Building osquery']
- ['development/contributing-code.md', 'Development', 'Contributing Code']
- ['development/creating-tables.md', 'Development', 'Creating New Tables']
- ['development/config-plugins.md', 'Development', 'Configuration Plugins']
- ['development/logger-plugins.md', 'Development', 'Logging Plugins']
- ['development/osquery-sdk.md', 'Development', 'SDK and Extensions']
- ['development/pubsub-framework.md', 'Development', 'Eventing Framework']
- ['development/unit-tests.md', 'Development', 'Writing Tests']
- ['development/options-arguments.md', 'Development', 'Adding CLI Arguments']
- ['development/reading-files.md', 'Development', 'Reading/Writing Files']
- ['development/wildcard-rules.md', 'Development', 'Wildcards and Globbing']
- ['development/kernel.md', 'Development', 'Kernel OS X']
