markdown: kramdown
highlighter: rouge
sass:
  style: compressed

repository: https://github.com/facebook/osquery
timezone: America/Los_Angeles
name: osquery â€¢ Performant Endpoint Visibility
description: Easily ask questions about your Linux, Windows, and macOS infrastructure
url: https://osquery.io

twitter:
  username: osquery

logo: /img/logo-2x.png

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"
  -
    scope:
      path: "_schema"
    values:
      layout: "schema"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  schema:
    permalink: /schema/:title/
    output: true

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - README.md

prefixes:
  darwin: pkg
  deb: linux.amd64.deb
  rpm: linux.x86_64.rpm
  linux: linux_x86_64.tar.gz

separators:
  darwin: "-"
  deb: "_"
  rpm: "-"
  linux: "-"

schema_url: https://raw.githubusercontent.com/osquery/osquery-site/master/schema
slack_url: https://osquery-slack.herokuapp.com
github_button:
  user: facebook
  repo: osquery
